download_file_info = {
    "duplicate": {
        "header": [
            "ACCOUNT PAYABLE ENTRY",
            "COMPANY",
            "INVOICE_DATE",
            "INVOICE NUMBER",
            "DUPLICATES_ID",
            "VENDOR_NAME",
            "VENDOR_NUMBER",
            "INVOICE_AMOUNT",
            "NO OF DUPLICATES",
            "POSTED DATE",
            "POSTED BY",
            "PAYMENT DATE",
            "RISK_SCORE",
            "REVIEW_STATUS",
        ],
        "column": [
            "ENTRY_ID",
            "COMPANY_NAME",
            "INVOICE_DATE",
            "INVOICE_NUMBER",
            "DUPLICATES_ID",
            "VENDOR_NAME",
            "VENDORID",
            "INVOICE_AMOUNT",
            "NO_OF_DUPLICATES",
            "POSTED_DATE",
            "POSTED_BY",
            "PAYMENT_DATE",
            "RISK_SCORE",
            "REVIEW_STATUS_CODE",
        ],
    },
    "accountdocument": {
        "header": [
            "ACCOUNT PAYABLE ENTRY",
            "INVOICE NUMBER",
            "COMPANY",
            "POSTED DATE",
            "INVOICE POSTING QUARTER",
            "DEBIT AMOUNT",
            "CREDIT AMOUNT",
            "POSTED BY",
            "RISK SCORE",
            "REVIEW STATUS",
            "DUE DATE",
            "PAYMENT DUE",
            "PAYMENT DELAY",
            "EARLY PAYMENT",
            "INVOICE QUARTER",
            "INVOICE_DATE",
            "EARLY INVOICE POSTING",
            "ACCOUNT_DOC_ID",
            "INVOICE_NUMBER",
            "COMPANY_CODE_NAME",
            "VENDOR_NAME",
            "VENDOR NUMBER",
            "TRANSACTION_ID",
            "TRANSACTION_CODE",
            "TRANSACTION_DESCRIPTION",
            "INVOICE_AMOUNT",
            "PAYMENT_TERMS",
            "TRANSACTION_DEBIT_AMOUNT",
            "TRANSACTION_CREDIT_AMOUNT",
        ],
        "column": [
            "ENTRY_ID",
            "INVOICE_NUMBER",
            "COMPANY_CODE_NAME",
            "POSTED_DATE",
            "QUARTER_POSTED_DATE",
            "DEBIT_AMOUNT",
            "CREDIT_AMOUNT",
            "POSTED_BY_NAME",
            "BLENDED_RISK_SCORE",
            "REVIEWSTATUSID",
            "DUE_DATE",
            "PAYMENT_DATE",
            "PAYMENT_DELAY",
            "EARLY_PAYMENT",
            "QUARTER_INVOICE_DATE",
            "INVOICE_DATE",
            "EARLY_INVOICE_POSTING",
            "ACCOUNT_DOC_ID",
            "INVOICE_NUMBER",
            "COMPANY_CODE_NAME",
            "VENDOR_NAME",
            "VENDORCODE",
            "TR_TRANSACTION_ID",
            "TR_TRANSACTION_CODE",
            "TR_TRANSACTION_DESCRIPTION",
            "TR_INVOICE_AMOUNT",
            "TR_PAYMENT_TERMS",
            "TR_DEBIT_AMOUNT",
            "TR_CREDIT_AMOUNT",
        ],
    },
    "accountdocumentsgl": {
        "header": [
            "Accounting Doc",
            "Company",
            "Posted Location",
            "Posted By",
            "Posted Date",
            "Debit Amount",
            "Credit Amount",
            "Risk Score",
            "Rules Breached",
            "Transaction Number",
            "Entered Location",
            "Entered Function",
            "Entered By",
            "Entered Date",
            "Account",
            "Account Description",
            "Transaction Debit Amount",
            "Transaction Credit Amount",
            "Transaction Risk Score",
            "Transaction Rules Breached",
        ],
        "column": [
            "ACCOUNTDOC_CODE",
            "COMPANY_CODE_NAME",
            "POSTED_LOCATION_NAME",
            "POSTED_BY_NAME",
            "POSTED_DATE",
            "DEBIT_AMOUNT",
            "CREDIT_AMOUNT",
            "BLENDED_RISK_SCORE",
            "CONTROL_DEVIATION",
            "TR_TRANSACTIONID",
            "TR_LOCATION_CODE",
            "TR_ENTERED_FUNCTION",
            "TR_ENTERED_BY_NAME",
            "TR_ENTERED_DATE",
            "TR_ACCOUNT_CODE",
            "TR_DESCRIPTION",
            "TR_DEBIT_AMOUNT",
            "TR_CREDIT_AMOUNT",
            "TR_BLENDED_RISK_SCORE",
            "TR_CONTROL_DEVIATION",
        ],
    },
    "casemanagementgl": {
        "header": [
            "Accounting Doc",
            "Company",
            "Posted Location",
            "Posted By",
            "Posted Date",
            "Debit Amount",
            "Credit Amount",
            "Risk Score",
            "Rules Breached",
            "Transaction Number",
            "Entered Location",
            "Entered Function",
            "Entered By",
            "Entered Date",
            "Account",
            "Account Description",
            "Transaction Debit Amount",
            "Transaction Credit Amount",
            "Transaction Risk Score",
            "Transaction Rules Breached",
        ],
        "column": [
            "ACCOUNTDOC_CODE",
            "COMPANY_CODE_NAME",
            "POSTED_LOCATION_NAME",
            "POSTED_BY_NAME",
            "POSTED_DATE",
            "DEBIT_AMOUNT",
            "CREDIT_AMOUNT",
            "BLENDED_RISK_SCORE",
            "CONTROL_DEVIATION",
            "TR_TRANSACTIONID",
            "TR_LOCATION_CODE",
            "TR_ENTERED_FUNCTION",
            "TR_ENTERED_BY_NAME",
            "TR_ENTERED_DATE",
            "TR_ACCOUNT_CODE",
            "TR_DESCRIPTION",
            "TR_DEBIT_AMOUNT",
            "TR_CREDIT_AMOUNT",
            "TR_BLENDED_RISK_SCORE",
            "TR_CONTROL_DEVIATION",
        ],
    },
    "transactiongl": {
        "header": [
            "Accounting Doc",
            "Company",
            "Posted Location",
            "Posted By",
            "Posted Date",
            "Debit Amount",
            "Credit Amount",
            "Risk Score",
            "Rules Breached",
            "Transaction Number",
            "Entered Location",
            "Entered Function",
            "Entered By",
            "Entered Date",
            "Account",
            "Account Description",
            "Transaction Debit Amount",
            "Transaction Credit Amount",
            "Transaction Risk Score",
            "TransactionRules Breached",
        ],
        "column": [
            "ACCOUNTDOC_CODE",
            "COMPANY_CODE_NAME",
            "POSTED_LOCATION_NAME",
            "POSTED_BY_NAME",
            "POSTED_DATE",
            "DEBIT_AMOUNT",
            "CREDIT_AMOUNT",
            "BLENDED_RISK_SCORE",
            "CONTROL_DEVIATION",
            "TR_TRANSACTIONID",
            "TR_LOCATION_CODE",
            "TR_ENTERED_FUNCTION",
            "TR_ENTERED_BY_NAME",
            "TR_ENTERED_DATE",
            "TR_ACCOUNT_CODE",
            "TR_DESCRIPTION",
            "TR_DEBIT_AMOUNT",
            "TR_CREDIT_AMOUNT",
            "TR_BLENDED_RISK_SCORE",
            "TR_CONTROL_DEVIATION",
        ],
    },
    "transactions": {
        "header": [
            "ACCOUNT NUMBER",
            "ACCOUNT NAME",
            "TRANSACTION CODE",
            "TRANSACTION ID",
            "ENTRY DATE",
            "POSTED DATE",
            "DEBIT AMOUNT",
            "CREDIT AMOUNT",
            "CONTROL DEVIATION",
            "RISK SCORE",
        ],
        "column": [
            "ACCOUNT_NUMBER",
            "TRANSACTION_DESC",
            "TRANSACTION_CODE",
            "TRANSACTION_ID",
            "ENTRY_DATE",
            "POSTING_DATE",
            "DEBIT_AMOUNT",
            "CREDIT_AMOUNT",
            "CONTROL_DEVIATION",
            "BLENDED_RISK_SCORE",
        ],
    },
}
