# Vim 1 log rename mappings



VIM_1LOG_RENAME_MAPPINGS = {
    'MANDT': 'CLIENT',
    'DOCID': 'VIM_1LOG_DOCUMENT_ID',
    'LOGID': 'VIM_1LOG_DOCUMENT_LOG_ID',
    'STATUS': 'VIM_1LOG_DOCUMENT_STATUS',
    'OPTIONID': 'VIM_1LOG_OPTION_ID',
    'FUNC_TEXT': 'VIM_1LOG_OPTION_TEXT',
    'ACTUAL_ROLE': 'VIM_1LOG_RESPONSIBLE_PARTY',
    'ACTUAL_AGENT': 'VIM_1LOG_ACTUAL_AGENT',
    'START_DATE': 'VIM_1LOG_ACTUAL_START_DATE',
    'START_TIME': 'VIM_1LOG_ACTUAL_START_TIME',
    'END_DATE': 'VIM_1LOG_ACTUAL_END_DATE',
    'END_TIME': 'VIM_1LOG_ACTUAL_END_TIME',
    'PROCESS_TYPE': 'VIM_1LOG_PROC_TYPE',
    'WORKITEM_ID': 'VIM_1LOG_WORKITEM_ID',
    'COMMEXIST': 'VIM_1LOG_COMMENTS_EXIST',
    'CANCELLED': 'VIM_1LOG_CANCELLED_FLAG',
    'S_LOGSYS': 'VIM_1LOG_SENDING_LOGSYS',
    'R_LOGSYS': 'VIM_1LOG_RECEIVING_LOGSYS',

}
