# VIM 8LOGCOMM  rename map

VIM_8LOGCOMM_RENAME_MAP = {
    'MANDT':'CLIENT',
    'BUS_OBJTYPE':'VIM_8LOG_OBJECT_TYPE',
    'BUS_OBJKEY':'VIM_8LOG_OBJECT_KEY',
    'Comments':'VIM_8LOG_COMMENTS',
    'LOGID':'VIM_8LOG_DOCUMENT_LOG_ID'
}
