# Vim 8 log rename mappings



VIM_8LOG_RENAME_MAPPINGS = {
    'MANDT': 'CLIENT',
    'BUS_OBJTYPE': 'VIM_8LOG_OBJECT_TYPE',
    'BUS_OBJKEY': 'VIM_8LOG_OBJECT_KEY',
    'LOGID': 'VIM_8LOG_DOCUMENT_LOG_ID',
    'FUNC_TEXT': 'VIM_8LOG_DESCRIPTION',
    'BLOCK_REASON': 'VIM_8LOG_BLOCK_REASON',
    'ACTUAL_ROLE': 'VIM_8LOG_RESPONSIBLE_PARTY',
    'ACTUAL_AGENT': 'VIM_8LOG_USER_NAME',
    'COMMEXIST': 'VIM_8LOG_COMMENTS_EXIST',
    'START_DATE': 'VIM_8LOG_ACTUAL_START_DATE',
    'START_TIME': 'VIM_8LOG_ACTUAL_START_TIME',
    'END_DATE': 'VIM_8LOG_ACTUAL_END_DATE',
    'END_TIME': 'VIM_8LOG_ACTUAL_END_TIME'
}