# LFA1 - Vendor General Data

LFA1_RENAME_COLUMNS = {
    'MANDT':'CLIENT',
    'LIFNR':'SUPPLIER_ID',
    'LAND1':'VENDOR_COUNTRY',
    'NAME1':'VENDOR_NAME',
    'NAME2':'VENDOR_NAME_2',
    'NAME3':'VENDOR_NAME_3',
    'NAME4':'VENDOR_NAME_4',
    'ORT01':'VENDOR_CITY',
    'PFACH':'VENDOR_PO_BOX',
    'PSTLZ':'VENDOR_POSTAL_CODE',
    'ORT02': 'VENDOR_DISTRICT',
    'PSTL2': 'VENDOR_PO_BOX_POSTAL_CODE',
    'REGIO':'VENDOR_REGION',
    'STRAS':'VENDOR_STREET',
    'LOEVM':'DELETION_FLAG',
    'STCD1':'VENDOR_TAX_NUMBER_1',
    'STCD2':'VENDOR_TAX_NUMBER_2',
    'STCEG':'VENDOR_VAT_REG_NO',
    'KTOKK':'VENDOR_ACCOUNT_GROUP',
    'ADRNR':'ADDRESS_ID',
    'STCD3':'VENDOR_TAX_NUMBER_3',
    'STCD4':'VENDOR_TAX_NUMBER_4',
    'STCD5':'VENDOR_TAX_NUMBER_5',
    'STCD6':'VENDOR_TAX_NUMBER_6',
    'ERDAT':'VENDOR_CREATED_ON'

}