# LFB1 - Vendor Master (Company Code)


LFB1_RENAME_COLUMNS = {
    'MANDT':'CLIENT',
    'LIFNR':'SUPPLIER_ID',
    'BUKRS':'COMPANY_CODE',
    'SPERR':'CO_CODE_BLOCK_INDICATOR',
    'LOEVM':'CO_CODE_DELETION_FLAG',
    'ZWELS':'PAYMENT_METHODS',
    'UZAWE':'PAYMENT_METHOD_SUPPLEMENT',
    'TOGRU':'TOLERANCE_GROUP',
    'ERDAT':'VENDOR_CO_CODE_CREATED_ON',
    'ChangeIndicator':'CHANGE_INDICATOR_LFB1',


}