from code1.logger import capture_log_message

def create_query_src_ap_data(audit_id):
    """
    This function creates SRC_AP_DATA dynamically query based on the audit id value
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Sql Query to create the table
    """
    table_name = "_SRC_AP_DATA_"+str(audit_id)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TRANSACTION_ID_GA` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `audit_id` int,
  `SUPPLIER_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SUPPLIER_ID` varchar(225) DEFAULT NULL,
  `AMOUNT` decimal(19,2) DEFAULT NULL,
  `INVOICE_AMOUNT` decimal(19,2) DEFAULT NULL,
  `INVOICE_DATE` datetime DEFAULT NULL,
  `INVOICE_NUMBER` varchar(150) DEFAULT NULL,
  `POSTED_DATE` datetime DEFAULT NULL,
  `REQUISITION_NUMBER` varchar(150) DEFAULT NULL,
  `REQUISITIONED_BY` varchar(150) DEFAULT NULL,
  `REQUISITION_DATE` datetime DEFAULT NULL,
  `TRANSPORTATION_DATE` datetime DEFAULT NULL,
  `PAYMENT_DATE` datetime DEFAULT NULL,
  `DUE_DATE` datetime DEFAULT NULL,
  `PAYMENT_METHOD` varchar(150) DEFAULT NULL,
  `PAYMENT_TERMS` varchar(150) DEFAULT NULL,
  `BANK_ROUTING_NUMBER` varchar(150) DEFAULT NULL,
  `PURCHASE_ORDER_NUMBER` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
  `PURCHASE_ORDER_AMOUNT` decimal(19,2) DEFAULT NULL,
  `PAYABLE_TYPE` varchar(150) DEFAULT NULL,
  `GL_ACCOUNT_TYPE` varchar(150) DEFAULT NULL,
  `ACCOUNT_DESCRIPTION` varchar(255) DEFAULT NULL,
  `DEBIT_CREDIT_INDICATOR` varchar(150) DEFAULT NULL,
  `ENTERED_BY` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `POSTED_BY` varchar(150) DEFAULT NULL,
  `POSTED_LOCATION` varchar(150) DEFAULT NULL,
  `COMPANY_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `DOCUMENTNO` varchar(150) DEFAULT NULL,
  `BASELINE_DATE` datetime DEFAULT NULL,
  `CLEARING_DOC` varchar(150) DEFAULT NULL,
  `CLEARING_DATE` datetime DEFAULT NULL,
  `RECEIVED_PAYMENT_TERMS` longtext,
  `RECEIVED_INVOICE_AMOUNT` float DEFAULT NULL,
  `RECEIVED_VENDOR_NAME` longtext,
  `RECEIVED_INVOICE_NUMBER` longtext,
  `PO_SUPPLIER` longtext,
  `PO_QUANTITY` int DEFAULT NULL,
  `PO_APPROVER` longtext,
  `PAYMENT_STATUS` longtext,
  `PAYMENT_REFERENCE_NUMBER` longtext,
  `PAYMENT_AMOUNT` float DEFAULT NULL,
  `ORDERED_MATERIAL` longtext,
  `MATERIAL_PRICE` float DEFAULT NULL,
  `JOURNEL_ENTRY_DESCRIPTION` longtext,
  `INVOICE_QUANTITY` int DEFAULT NULL,
  `GRN_QUANTITY` int DEFAULT NULL,
  `ENTRY_TYPE` longtext,
  `ENTERED_DATE` datetime DEFAULT NULL,
  `DEBIT_MEMO_AMOUNT` float DEFAULT NULL,
  `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `CREDIT_MEMO_AMOUNT` float DEFAULT NULL,
  `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `APPROVED_USER_5` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `APPROVED_USER_4` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `APPROVED_USER_3` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `APPROVED_USER_2` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `APPROVED_USER_1` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `APPROVED_DESIGNATION_LEVEL_5` longtext,
  `APPROVED_DESIGNATION_LEVEL_4` longtext,
  `APPROVED_DESIGNATION_LEVEL_3` longtext,
  `APPROVED_DESIGNATION_LEVEL_2` longtext,
  `APPROVED_DESIGNATION_LEVEL_1` longtext,
  `APPROVED` binary(1) DEFAULT NULL,
  `ADJUSTMENT_AMOUNT` float DEFAULT NULL,
  `ACCOUNTING_DATE` datetime DEFAULT NULL,
  `CREDIT_PERIOD` int DEFAULT NULL,
  `ACCOUNTING_DOC` varchar(255) DEFAULT NULL,
  `TRANSACTION_ID` varchar(250) DEFAULT NULL,
  `POSTED_BY_ORG_CHART_UNIT` varchar(255) DEFAULT NULL,
  `POSTED_BY_USER_TYPE` varchar(255) DEFAULT NULL,
  `POSTED_BY_DEPARTMENT` varchar(255) DEFAULT NULL,
  `POSTED_BY_POSITION` varchar(250) DEFAULT NULL,
  `TRANSACTION_DESCRIPTION` varchar(255) DEFAULT NULL,
  `INVOICE_STATUS` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DOC_TYPE` varchar(150) DEFAULT NULL,
  `ENTERED_LOCATION` varchar(150) DEFAULT NULL,
  `DOC_TYPE_DESCRIPTION` varchar(155) DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `DISCOUNT_PERIOD` int DEFAULT NULL,
  `DISCOUNT_TAKEN` varchar(155) DEFAULT NULL,
  `GRN_DATE` datetime DEFAULT NULL,
  `GRN_NUMBER` varchar(225) DEFAULT NULL,
  `INVOICE_PRICE` float DEFAULT NULL,
  `PO_PRICE` float DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """.format(table_name)
    
    return create_query



def create_query_ap_transaction(audit_id):
    """
    This function is used to dynamically create ap_transaction table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """    
    table_name = 'ap_transaction_'+str(audit_id)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
  `TRANSACTION_ID` int NOT NULL,
  `audit_id` int,
  `TRANSACTION_CODE` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ENTERED_BY` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INVOICE_ID` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACCOUNT_DOC_ID` bigint DEFAULT NULL,
  `TRANSACTION_DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `GL_ACCOUNT_DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `PAYMENT_DATE` datetime DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
  `ACCOUNT_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACCOUNT_TYPE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SYSTEM_VOUCHER_NUMBER` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ENTRY_TYPE_ID` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `POSTED_BY` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `POSTING_DATE` datetime DEFAULT NULL,
  `ENTRY_DATE` datetime DEFAULT NULL,
  `SYSTEM_UPDATED_DATE` datetime DEFAULT NULL,
  `IS_SCORED` tinyint DEFAULT '0',
  `CREDIT_PERIOD` int DEFAULT NULL,
  `DUE_DATE` datetime DEFAULT NULL,
  `COMPANY_ID` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SUPPLIER_ID` varchar(225) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `LOCATION_ID` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REQUISITION_DATE` datetime DEFAULT NULL,
  `INVOICE_DATE` datetime DEFAULT NULL,
  `INVOICE_AMOUNT` float DEFAULT NULL,
  `INVOICE_NUMBER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `AXIOM_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VOUCHER_TYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PAYMENT_TERMS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VENDORID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACCOUNT_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `DISCOUNT_PERIOD` int DEFAULT NULL,
  `DISCOUNT_TAKEN` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PURCHASE_ORDER_NUMBER` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INVOICE_PRICE` float DEFAULT NULL,
  `PO_PRICE` float DEFAULT NULL,
  `INVOICE_QUANTITY` int DEFAULT NULL,
  `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
  `GRN_NUMBER` int DEFAULT NULL,
  `GRN_DATE` datetime DEFAULT NULL,
  `PO_QUANTITY` int DEFAULT NULL,
  `DOC_TYPE` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PAYMENT_AMOUNT` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `AMOUNT` float DEFAULT NULL,
  `PAYMENT_METHOD` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TRANSPORTATION_DATE` datetime DEFAULT NULL,
  `PAYMENT_BLOCK_STATUS` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_ID`),
  KEY `idx_aptr_axiomid` (`TRANSACTION_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """.format(table_name)
    
    return create_query


def create_query_ap_account_document(audit_id):
    """
    This function is used to dynamically create ap_accountdocument table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """    
    table_name = "ap_accountdocuments_"+str(audit_id)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
  `ACCOUNT_DOC_ID` bigint unsigned NOT NULL,
  `ENTRY_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `audit_id` int,
  `ENTRY_TYPE_ID` int DEFAULT NULL,
  `INVOICE_NUMBER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INVOICE_DATE` datetime DEFAULT NULL,
  `INVOICE_AMOUNT` decimal(19,4) DEFAULT NULL,
  `VENDORID` int DEFAULT NULL,
  `AMOUNT` decimal(19,4) DEFAULT NULL,
  `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `COMPANYID` int DEFAULT NULL,
  `LOCATIONID` int DEFAULT NULL,
  `ENTERED_DATE` datetime DEFAULT NULL,
  `POSTED_DATE` datetime DEFAULT NULL,
  `ENTERED_BY` int DEFAULT NULL,
  `POSTED_BY` int DEFAULT NULL,
  `PAYMENT_DATE` datetime DEFAULT NULL,
  `DUE_DATE` datetime DEFAULT NULL,
  `PAYMENT_TERMS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CREDIT_PERIOD` int DEFAULT NULL,
  `IS_SCORED` tinyint DEFAULT '0',
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACCOUNT_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REVIEWSTATUSID` tinyint DEFAULT '1',
  `APPROVED_USER_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `APPROVED_USER_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `APPROVED_USER_3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `APPROVED_USER_4` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `APPROVED_USER_5` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `APPROVAL_MATRIX_ID` int DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_DOC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    
    """.format(table_name)
    
    return create_query



def create_query_ap_transaction_flat(mth_year):
    """
    This function is used to dynamically create aptransactionflat table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """
    
    table_name = "aptransactionflat_"+str(mth_year)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    
    CREATE TABLE IF NOT EXISTS {} (
  `audit_id` int,
  `TRANSACTION_ID` int DEFAULT NULL,
  `ACCOUNT_DOC_ID` int DEFAULT NULL,
  `CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `PAYMENT_DATE` datetime DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
  `ENTRY_DATE` datetime DEFAULT NULL,
  `TRANSACTION_CODE` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `POSTING_DATE` datetime DEFAULT NULL,
  `TRANSACTION_DESC` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `AI_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE_INDEXED` decimal(19,4) DEFAULT NULL,
  `ENTRY_LOCATION` varchar(150) DEFAULT NULL,
  `ENTERED_BY_NAME` varchar(150) DEFAULT NULL,
  `INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `DUPLICATE_INVOICE_POSTING` tinyint DEFAULT NULL,
  `LATE_PAYMENT` tinyint DEFAULT NULL,
  `EXCESS_PAYMENT` tinyint DEFAULT NULL,
  `LOST_DISCOUNT` tinyint DEFAULT NULL,
  `UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `POSTING_PERIOD` tinyint DEFAULT NULL,
  `DATE_SEQUENTIAL_MISMATCH` tinyint DEFAULT NULL,
  `WORK_FLOW_DEVIATION` tinyint DEFAULT NULL,
  `TWO_DIGIT_BENFORD` tinyint DEFAULT NULL,
  `UNUSUAL_SUPPLIER_ACTIVITY` tinyint DEFAULT NULL,
  `INVOICE_CREATED_AFTER_ACCOUNTING_DATE` tinyint DEFAULT NULL,
  `INVOICE_VALUE_OF_SUPPLIER` tinyint DEFAULT NULL,
  `3_WAY_MATCHING` tinyint DEFAULT NULL,
  `NON_PO_INVOICE` tinyint DEFAULT NULL,
  `SEGGREGATION_OF_DUTIES` tinyint DEFAULT NULL,
  `SIGNIFICANT_DELAY_IN_DELIVERY` tinyint DEFAULT NULL,
  `UNUSUAL_VENDOR` tinyint DEFAULT NULL,
  `MANUAL_DEBIT_OR_CREDIT_NOTES` tinyint DEFAULT NULL,
  `ROUNDING_OFF` tinyint DEFAULT NULL,
  `TRANSACTION_TEXT_EMPTY` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_LATE_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `OPTIMISED_SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `OPTIMISED_IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `OPTIMISED_POSTING_PERIOD` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `OPTIMISED_NON_PO_INVOICE` tinyint DEFAULT NULL,
  `OPTIMISED_INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `OPTIMISED_3_WAY_MATCHING` tinyint DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `OPTIMISED_DEVIATION` tinyint DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `ENTERED_BY` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACCOUNT_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INVOICE_ID` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GL_ACCOUNT_DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `POSTED_BY` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `BLENDED_RISK_SCORE` double DEFAULT NULL,
  `COMMENTS` bigint DEFAULT NULL,
  `EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `OLD_UNPAID_INVOICE` tinyint DEFAULT NULL,
  `APPROVAL_MATRIX` tinyint DEFAULT NULL,
  `VENDOR_MASTER_CHANGES` tinyint DEFAULT NULL,
  `PAYMENT_BLOCK_R` tinyint DEFAULT NULL,
  `EARLY_PAYMENT` tinyint DEFAULT NULL,
  `ACCOUNT_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COMPANYID` int DEFAULT NULL,
  `PAYMENT_TERMS` varchar(150) DEFAULT NULL,
  `INVOICE_AMOUNT` decimal(19,2) DEFAULT NULL,
  `DOC_TYPE` varchar(150) DEFAULT NULL,
  `PURCHASE_ORDER_NUMBER` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `GRN_NUMBER` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `GRN_DATE` datetime DEFAULT NULL,
  `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
  `DISCOUNT_PERCENTAGE_1` decimal(19,2) DEFAULT NULL,
  `DISCOUNT_PERCENTAGE_2` decimal(19,2) DEFAULT NULL,
  `DISCOUNT_TAKEN` tinyint DEFAULT NULL,
  `DISCOUNT_PERIOD_1` int DEFAULT NULL,
  `DISCOUNT_PERIOD_2` int DEFAULT NULL,
  `CREDIT_PERIOD` int DEFAULT NULL,
  `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `TRANSACTION_ID` (`TRANSACTION_ID`) USING BTREE,
  KEY `accountdo_idx` (`ACCOUNT_DOC_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    """.format(table_name)
    
    return create_query


def create_query_ap_account_document_flat(mth_year):
    """
    This function is used to dynamically create apaccountdocumentflat table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """    
    table_name = "apaccountdocumentsflat_"+str(mth_year)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
  `audit_id` int,
  `PAYMENT_DATE` datetime DEFAULT NULL,
  `DUE_DATE` datetime DEFAULT NULL,
  `GRN_DATE` datetime DEFAULT NULL,
  `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
  `INVOICE_DATE` datetime DEFAULT NULL,
  `INVOICE_NUMBER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACCOUNT_DOC_SCORE_ID` bigint unsigned NOT NULL DEFAULT '0',
  `ACCOUNT_DOC_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DEVIATION` tinyint DEFAULT NULL,
  `BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `AI_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `AI_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE_INDEXED` decimal(19,4) DEFAULT NULL,
  `RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `DUPLICATE_INVOICE_POSTING` tinyint DEFAULT NULL,
  `LATE_PAYMENT` tinyint DEFAULT NULL,
  `EXCESS_PAYMENT` tinyint DEFAULT NULL,
  `LOST_DISCOUNT` tinyint DEFAULT NULL,
  `UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `POSTING_PERIOD` tinyint DEFAULT NULL,
  `DATE_SEQUENTIAL_MISMATCH` tinyint DEFAULT NULL,
  `WORK_FLOW_DEVIATION` tinyint DEFAULT NULL,
  `TWO_DIGIT_BENFORD` tinyint DEFAULT NULL,
  `UNUSUAL_SUPPLIER_ACTIVITY` tinyint DEFAULT NULL,
  `INVOICE_CREATED_AFTER_ACCOUNTING_DATE` tinyint DEFAULT NULL,
  `INVOICE_VALUE_OF_SUPPLIER` tinyint DEFAULT NULL,
  `3_WAY_MATCHING` tinyint DEFAULT NULL,
  `NON_PO_INVOICE` tinyint DEFAULT NULL,
  `SEGGREGATION_OF_DUTIES` tinyint DEFAULT NULL,
  `SIGNIFICANT_DELAY_IN_DELIVERY` tinyint DEFAULT NULL,
  `UNUSUAL_VENDOR` tinyint DEFAULT NULL,
  `MANUAL_DEBIT_OR_CREDIT_NOTES` tinyint DEFAULT NULL,
  `ROUNDING_OFF` tinyint DEFAULT NULL,
  `TRANSACTION_TEXT_EMPTY` tinyint DEFAULT NULL,
  `STATUS` tinyint DEFAULT NULL,
  `ENTRY_ID` varchar(255) DEFAULT NULL,
  `ENTRY_TYPE_ID` int DEFAULT NULL,
  `VENDORID` int DEFAULT NULL,
  `POSTED_DATE` datetime DEFAULT NULL,
  `COMPANYID` int DEFAULT NULL,
  `LOCATIONID` int DEFAULT NULL,
  `POSTED_LOCATION_NAME` varchar(150) DEFAULT NULL,
  `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
  `POSTED_BY_NAME` varchar(150) DEFAULT NULL,
  `COMPANY_CODE_NAME` varchar(150) DEFAULT NULL,
  `REVIEWSTATUSID` int NOT NULL DEFAULT '0',
  `REVIEW_STATUS_CODE` varchar(150) DEFAULT NULL,
  `COMMENTS` bigint NOT NULL DEFAULT '0',
  `ASSIGNED_TO` int DEFAULT NULL,
  `ASSIGNED_BY` int DEFAULT NULL,
  `ISDEVIATION` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_LATE_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `OPTIMISED_SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `OPTIMISED_IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `OPTIMISED_POSTING_PERIOD` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `OPTIMISED_NON_PO_INVOICE` tinyint DEFAULT NULL,
  `OPTIMISED_INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `OPTIMISED_3_WAY_MATCHING` tinyint DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `OPTIMISED_DEVIATION` tinyint DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `SELECTED_TRANSACTIONS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SUB_R_STATUS_CODE` varchar(150) DEFAULT NULL,
  `SUBRSTATUSID` int DEFAULT NULL,
  `EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `OLD_UNPAID_INVOICE` tinyint DEFAULT NULL,
  `APPROVED_USER_1` varchar(225) DEFAULT NULL,
  `APPROVED_USER_2` varchar(225) DEFAULT NULL,
  `APPROVED_USER_3` varchar(225) DEFAULT NULL,
  `APPROVED_USER_4` varchar(225) DEFAULT NULL,
  `APPROVED_USER_5` varchar(225) DEFAULT NULL,
  `APPROVAL_MATRIX_ID` int DEFAULT NULL,
  `APPROVAL_MATRIX` tinyint DEFAULT NULL,
  `VENDOR_MASTER_CHANGES` tinyint DEFAULT NULL,
  `VENDORCODE` varchar(100) DEFAULT NULL,
  `PAYMENT_BLOCK_R` tinyint DEFAULT NULL,
  `EARLY_PAYMENT` tinyint DEFAULT NULL,
  `POSTED_BY` int DEFAULT NULL,
  `PAYMENT_TERMS` varchar(150) DEFAULT NULL,
  `INVOICE_AMOUNT` decimal(19,2) DEFAULT NULL,
  `DOC_TYPE` varchar(150) DEFAULT NULL,
  `PURCHASE_ORDER_NUMBER` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `GRN_NUMBER` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `DISCOUNT_PERCENTAGE_1` decimal(19,2) DEFAULT NULL,
  `DISCOUNT_PERCENTAGE_2` decimal(19,2) DEFAULT NULL,
  `DISCOUNT_TAKEN` tinyint DEFAULT NULL,
  `DISCOUNT_PERIOD_1` int DEFAULT NULL,
  `DISCOUNT_PERIOD_2` int DEFAULT NULL,
  `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREDIT_PERIOD` int DEFAULT NULL,
  `AMOUNT` decimal(19,2) DEFAULT NULL,
  `INVOICE_CURRENCY` varchar(255) DEFAULT NULL,
  `PAYMENT_METHOD` varchar(255) DEFAULT NULL,
  `VAT_ID` varchar(255) DEFAULT NULL,
  `LEGAL_ENTITY_NAME_AND_ADDRESS` varchar(255) DEFAULT NULL,
  UNIQUE KEY `primary_key` (`ACCOUNT_DOC_ID`) USING BTREE,
  KEY `posted_date` (`POSTED_DATE`) USING BTREE,
  KEY `companyid` (`COMPANYID`) USING BTREE,
  KEY `vendorid` (`VENDORID`) USING BTREE,
  KEY `reviewstatus` (`REVIEWSTATUSID`) USING BTREE,
  KEY `debit` (`DEBIT_AMOUNT`) USING BTREE,
  KEY `credit` (`CREDIT_AMOUNT`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    """.format(table_name)
    
    
    return create_query


def create_query_ap_transaction_score(audit_id):
    """
    This function is used to dynamically create ap_transaction_score table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """
    
    table_name ="ap_transactionscore_"+str(audit_id)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
  `TRANSACTION_SCORE_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `audit_id` int,
  `TRANSACTION_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DEVIATION` tinyint DEFAULT NULL,
  `BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `AI_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `AI_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE_INDEXED` decimal(19,4) DEFAULT NULL,
  `RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `DUPLICATE_INVOICE_POSTING` tinyint DEFAULT NULL,
  `LATE_PAYMENT` tinyint DEFAULT NULL,
  `EXCESS_PAYMENT` tinyint DEFAULT NULL,
  `LOST_DISCOUNT` tinyint DEFAULT NULL,
  `UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `POSTING_PERIOD` tinyint DEFAULT NULL,
  `DATE_SEQUENTIAL_MISMATCH` tinyint DEFAULT NULL,
  `WORK_FLOW_DEVIATION` tinyint DEFAULT NULL,
  `TWO_DIGIT_BENFORD` tinyint DEFAULT NULL,
  `UNUSUAL_SUPPLIER_ACTIVITY` tinyint DEFAULT NULL,
  `INVOICE_CREATED_AFTER_ACCOUNTING_DATE` tinyint DEFAULT NULL,
  `INVOICE_VALUE_OF_SUPPLIER` tinyint DEFAULT NULL,
  `3_WAY_MATCHING` tinyint DEFAULT NULL,
  `NON_PO_INVOICE` tinyint DEFAULT NULL,
  `SEGGREGATION_OF_DUTIES` tinyint DEFAULT NULL,
  `SIGNIFICANT_DELAY_IN_DELIVERY` tinyint DEFAULT NULL,
  `UNUSUAL_VENDOR` tinyint DEFAULT NULL,
  `MANUAL_DEBIT_OR_CREDIT_NOTES` tinyint DEFAULT NULL,
  `ROUNDING_OFF` tinyint DEFAULT NULL,
  `TRANSACTION_TEXT_EMPTY` tinyint DEFAULT NULL,
  `STATUS` tinyint DEFAULT NULL,
  `ACCOUNT_DOC_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `DIFFERENCE_IN_INVOICE_QUANTITY` tinyint DEFAULT NULL,
  `DIFFERENCE_IN_INVOICE_PRICE` tinyint DEFAULT NULL,
  `HIGH_VALUE_DEBIT_CREDIT_NOTES` tinyint DEFAULT NULL,
  `ADVANCE_PAYMENT_AGAINST_INVOICES` tinyint DEFAULT NULL,
  `EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `CASH_REIMBURSEMENTS` tinyint DEFAULT NULL,
  `CASH_EXPENSES` tinyint DEFAULT NULL,
  `OLD_UNPAID_INVOICE` tinyint DEFAULT NULL,
  `APPROVAL_MATRIX` tinyint DEFAULT NULL,
  `VENDOR_MASTER_CHANGES` tinyint DEFAULT NULL,
  `PAYMENT_BLOCK_R` tinyint DEFAULT NULL,
  `EARLY_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_LATE_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `OPTIMISED_SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `OPTIMISED_IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `OPTIMISED_POSTING_PERIOD` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `OPTIMISED_NON_PO_INVOICE` tinyint DEFAULT NULL,
  `OPTIMISED_INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `OPTIMISED_3_WAY_MATCHING` tinyint DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `OPTIMISED_DEVIATION` tinyint DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_SCORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    
    """.format(table_name)
    
    return create_query


def create_query_ap_acc_doc_score(audit_id):
    """
    This function dynamically creates apaccountdocscore table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """
    
    table_name = "ap_accountdocscore_"+str(audit_id)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
  `ACCOUNT_DOC_SCORE_ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `audit_id` int,
  `ACCOUNT_DOC_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DEVIATION` tinyint DEFAULT NULL,
  `BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `AI_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `AI_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE` decimal(19,4) DEFAULT NULL,
  `STAT_SCORE_INDEXED` decimal(19,4) DEFAULT NULL,
  `RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `DUPLICATE_INVOICE_POSTING` tinyint DEFAULT NULL,
  `LATE_PAYMENT` tinyint DEFAULT NULL,
  `EXCESS_PAYMENT` tinyint DEFAULT NULL,
  `LOST_DISCOUNT` tinyint DEFAULT NULL,
  `UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `POSTING_PERIOD` tinyint DEFAULT NULL,
  `DATE_SEQUENTIAL_MISMATCH` tinyint DEFAULT NULL,
  `WORK_FLOW_DEVIATION` tinyint DEFAULT NULL,
  `TWO_DIGIT_BENFORD` tinyint DEFAULT NULL,
  `UNUSUAL_SUPPLIER_ACTIVITY` tinyint DEFAULT NULL,
  `INVOICE_CREATED_AFTER_ACCOUNTING_DATE` tinyint DEFAULT NULL,
  `INVOICE_VALUE_OF_SUPPLIER` tinyint DEFAULT NULL,
  `3_WAY_MATCHING` tinyint DEFAULT NULL,
  `NON_PO_INVOICE` tinyint DEFAULT NULL,
  `SEGGREGATION_OF_DUTIES` tinyint DEFAULT NULL,
  `SIGNIFICANT_DELAY_IN_DELIVERY` tinyint DEFAULT NULL,
  `UNUSUAL_VENDOR` tinyint DEFAULT NULL,
  `MANUAL_DEBIT_OR_CREDIT_NOTES` tinyint DEFAULT NULL,
  `ROUNDING_OFF` tinyint DEFAULT NULL,
  `TRANSACTION_TEXT_EMPTY` tinyint DEFAULT NULL,
  `STATUS` tinyint DEFAULT NULL,
  `HIGH_VALUE_DEBIT_CREDIT_NOTES` tinyint DEFAULT NULL,
  `DIFFERENCE_IN_INVOICE_PRICE` tinyint DEFAULT NULL,
  `DIFFERENCE_IN_INVOICE_QUANTITY` tinyint DEFAULT NULL,
  `INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `ADVANCE_PAYMENT_AGAINST_INVOICES` tinyint DEFAULT NULL,
  `EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `CASH_REIMBURSEMENTS` tinyint DEFAULT NULL,
  `CASH_EXPENSES` tinyint DEFAULT NULL,
  `OLD_UNPAID_INVOICE` tinyint DEFAULT NULL,
  `APPROVAL_MATRIX` tinyint DEFAULT NULL,
  `VENDOR_MASTER_CHANGES` tinyint DEFAULT NULL,
  `PAYMENT_BLOCK_R` tinyint DEFAULT NULL,
  `EARLY_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_LATE_PAYMENT` tinyint DEFAULT NULL,
  `OPTIMISED_UNFAVORABLE_PAYMENT_TERMS` tinyint DEFAULT NULL,
  `OPTIMISED_SUSPICIOUS_KEYWORD` tinyint DEFAULT NULL,
  `OPTIMISED_IMMEDIATE_PAYMENTS` tinyint DEFAULT NULL,
  `OPTIMISED_POSTING_PERIOD` tinyint DEFAULT NULL,
  `OPTIMISED_EARLY_POSTED_INVOICES` tinyint DEFAULT NULL,
  `OPTIMISED_NON_PO_INVOICE` tinyint DEFAULT NULL,
  `OPTIMISED_INVOICES_WITHOUT_GRN` tinyint DEFAULT NULL,
  `OPTIMISED_3_WAY_MATCHING` tinyint DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_RULES_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_CONTROL_DEVIATION` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `OPTIMISED_DEVIATION` tinyint DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE` decimal(19,4) DEFAULT NULL,
  `OPTIMISED_BLENDED_RISK_SCORE_RAW` decimal(19,4) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_DOC_SCORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;    
    """.format(table_name)
    
    return create_query


def create_query_hist_parquet_data(table_name):
    
   capture_log_message(f'Creating table {table_name}')


   create_table_sql = f"""
           CREATE TABLE IF NOT EXISTS `{table_name}` (
               `ID` int NOT NULL AUTO_INCREMENT,
               `TRANSACTION_ID_GA` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
               `audit_id` int DEFAULT NULL,
               `SUPPLIER_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
               `SUPPLIER_ID` varchar(225) DEFAULT NULL,
               `AMOUNT` decimal(19,2) DEFAULT NULL,
               `INVOICE_AMOUNT` decimal(19,2) DEFAULT NULL,
               `INVOICE_DATE` datetime DEFAULT NULL,
               `INVOICE_NUMBER` varchar(150) DEFAULT NULL,
               `POSTED_DATE` datetime DEFAULT NULL,
               `REQUISITION_NUMBER` varchar(150) DEFAULT NULL,
               `REQUISITIONED_BY` varchar(150) DEFAULT NULL,
               `REQUISITION_DATE` datetime DEFAULT NULL,
               `TRANSPORTATION_DATE` datetime DEFAULT NULL,
               `PAYMENT_DATE` datetime DEFAULT NULL,
               `DUE_DATE` datetime DEFAULT NULL,
               `PAYMENT_METHOD` varchar(150) DEFAULT NULL,
               `PAYMENT_TERMS` varchar(150) DEFAULT NULL,
               `BANK_ROUTING_NUMBER` varchar(150) DEFAULT NULL,
               `PURCHASE_ORDER_NUMBER` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
               `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
               `PURCHASE_ORDER_AMOUNT` decimal(19,2) DEFAULT NULL,
               `PAYABLE_TYPE` varchar(150) DEFAULT NULL,
               `GL_ACCOUNT_TYPE` varchar(150) DEFAULT NULL,
               `ACCOUNT_DESCRIPTION` varchar(255) DEFAULT NULL,
               `DEBIT_CREDIT_INDICATOR` varchar(150) DEFAULT NULL,
               `ENTERED_BY` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
               `POSTED_BY` varchar(150) DEFAULT NULL,
               `POSTED_LOCATION` varchar(150) DEFAULT NULL,
               `COMPANY_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
               `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
               `CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
               `DOCUMENTNO` varchar(150) DEFAULT NULL,
               `BASELINE_DATE` datetime DEFAULT NULL,
               `CLEARING_DOC` varchar(150) DEFAULT NULL,
               `CLEARING_DATE` datetime DEFAULT NULL,
               `RECEIVED_PAYMENT_TERMS` longtext,
               `RECEIVED_INVOICE_AMOUNT` float DEFAULT NULL,
               `RECEIVED_VENDOR_NAME` longtext,
               `RECEIVED_INVOICE_NUMBER` longtext,
               `PO_SUPPLIER` longtext,
               `PO_QUANTITY` int DEFAULT NULL,
               `PO_APPROVER` longtext,
               `PAYMENT_STATUS` longtext,
               `PAYMENT_REFERENCE_NUMBER` longtext,
               `PAYMENT_AMOUNT` float DEFAULT NULL,
               `ORDERED_MATERIAL` longtext,
               `MATERIAL_PRICE` float DEFAULT NULL,
               `JOURNEL_ENTRY_DESCRIPTION` longtext,
               `INVOICE_QUANTITY` int DEFAULT NULL,
               `GRN_QUANTITY` int DEFAULT NULL,
               `ENTRY_TYPE` longtext,
               `ENTERED_DATE` datetime DEFAULT NULL,
               `DEBIT_MEMO_AMOUNT` float DEFAULT NULL,
               `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
               `CREDIT_MEMO_AMOUNT` float DEFAULT NULL,
               `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
               `APPROVED_USER_5` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
               `APPROVED_USER_4` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
               `APPROVED_USER_3` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
               `APPROVED_USER_2` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
               `APPROVED_USER_1` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
               `APPROVED_DESIGNATION_LEVEL_5` longtext,
               `APPROVED_DESIGNATION_LEVEL_4` longtext,
               `APPROVED_DESIGNATION_LEVEL_3` longtext,
               `APPROVED_DESIGNATION_LEVEL_2` longtext,
               `APPROVED_DESIGNATION_LEVEL_1` longtext,
               `APPROVED` binary(1) DEFAULT NULL,
               `ADJUSTMENT_AMOUNT` float DEFAULT NULL,
               `ACCOUNTING_DATE` datetime DEFAULT NULL,
               `CREDIT_PERIOD` int DEFAULT NULL,
               `ACCOUNTING_DOC` varchar(255) DEFAULT NULL,
               `TRANSACTION_ID` varchar(250) DEFAULT NULL,
               `POSTED_BY_ORG_CHART_UNIT` varchar(255) DEFAULT NULL,
               `POSTED_BY_USER_TYPE` varchar(255) DEFAULT NULL,
               `POSTED_BY_DEPARTMENT` varchar(255) DEFAULT NULL,
               `POSTED_BY_POSITION` varchar(250) DEFAULT NULL,
               `TRANSACTION_DESCRIPTION` varchar(255) DEFAULT NULL,
               `INVOICE_STATUS` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
               `DOC_TYPE` varchar(150) DEFAULT NULL,
               `ENTERED_LOCATION` varchar(150) DEFAULT NULL,
               `DOC_TYPE_DESCRIPTION` varchar(155) DEFAULT NULL,
               `DISCOUNT_PERCENTAGE_1` float DEFAULT NULL,
               `DISCOUNT_PERIOD_1` int DEFAULT NULL,
               `DISCOUNT_PERCENTAGE_2` float DEFAULT NULL,
               `DISCOUNT_PERIOD_2` int DEFAULT NULL,
               `DISCOUNT_TAKEN` varchar(155) DEFAULT NULL,
               `GRN_DATE` datetime DEFAULT NULL,
               `GRN_NUMBER` varchar(225) DEFAULT NULL,
               `INVOICE_PRICE` float DEFAULT NULL,
               `PO_PRICE` float DEFAULT NULL,
               PRIMARY KEY (`ID`)
           ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
           """
   return create_table_sql


def create_query_duplicate_invoices(mth_year):
   """
   This function is used to dynamically create duplicate_invoices table query based on audit id
  
   Args:
       audit_id : Audit id number
      
   Returns:
       Mysql Create Query
   """
   table_name = "duplicate_invoices_"+str(mth_year)
   capture_log_message(f'Creating {table_name}')
   create_query = f"""
   CREATE TABLE IF NOT EXISTS {table_name} (
 `DUPLICATES_ID` int DEFAULT NULL,
 `ID` int NOT NULL AUTO_INCREMENT,
 `audit_id` int DEFAULT NULL,
 `SCENARIO_ID` INT DEFAULT NULL,
 `RISK_SCORE` varchar(45) DEFAULT NULL,
  `DEBIT_CREDIT_INDICATOR` varchar(10) DEFAULT NULL,
 `PURCHASE_ORDER_NUMBER` varchar(100) DEFAULT NULL,
 `OPTIMIZED_RISK_SCORE` varchar(45) DEFAULT NULL,
 `ACCOUNT_DOC_ID` varchar(450) DEFAULT NULL,
 `ENTRY_ID` varchar(45) DEFAULT NULL,
 `ENTRY_TYPE_ID` varchar(45) DEFAULT NULL,
 `INVOICE_NUMBER` varchar(450) DEFAULT NULL,
 `INVOICE_DATE` datetime DEFAULT NULL,
 `INVOICE_AMOUNT` varchar(450) DEFAULT NULL,
 `VENDORCODE` varchar(45)  DEFAULT NULL,
 `VENDOR_NAME` varchar(500) DEFAULT NULL,
 `AMOUNT` varchar(45) DEFAULT NULL,
 `DEBIT_AMOUNT` varchar(45) DEFAULT NULL,
 `CREDIT_AMOUNT` varchar(45) DEFAULT NULL,
 `COMPANYID` bigint DEFAULT NULL,
 `LOCATIONID` varchar(45) DEFAULT NULL,
 `ENTERED_DATE` datetime DEFAULT NULL,
 `POSTED_DATE` datetime DEFAULT NULL,
 `ENTERED_BY` varchar(45) DEFAULT NULL,
 `PAYMENT_DATE` datetime DEFAULT NULL,
 `DUE_DATE` datetime DEFAULT NULL,
 `PAYMENT_TERMS` varchar(500) DEFAULT NULL,
 `CREDIT_PERIOD` varchar(45) DEFAULT NULL,
 `CREATED_DATE` datetime DEFAULT NULL,
 `MODIFIED_DATE` varchar(45) DEFAULT NULL,
 `ACCOUNT_ID` varchar(45) DEFAULT NULL,
 `REVIEWSTATUSID` int DEFAULT '5',
 `PrimaryKeySimple` varchar(450) DEFAULT NULL,
 `INVOICE_NUMBER_FORMAT` varchar(450) DEFAULT NULL,
 `INVOICE_AMOUNT_ABS` varchar(45) DEFAULT NULL,
 `COMPANY` varchar(45) DEFAULT NULL,
 `IS_SCORED` varchar(45) DEFAULT NULL,
 `NO_OF_DUPLICATES` varchar(45) DEFAULT NULL,
 `VENDORID` int DEFAULT NULL,
 `POSTED_BY` int DEFAULT NULL,
 `INVOICE_CATEGORY` varchar(45) DEFAULT NULL,
 `is_current_data` bool DEFAULT NULL,
 `REGION` VARCHAR(50) DEFAULT NULL,
 `DOC_TYPE` VARCHAR(50) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 KEY `inv_date_idx` (`INVOICE_DATE`) USING BTREE,
 KEY `posted_date_idx` (`POSTED_DATE`) USING BTREE,
 KEY `reviewstatus_idx` (`REVIEWSTATUSID`) USING BTREE,
 KEY `compnay_idx` (`COMPANYID`) USING BTREE,
 KEY `vendor_idx` (`VENDORID`) USING BTREE,
 KEY `scenario_id_idx` (`SCENARIO_ID`) USING BTREE,

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
   """
  

#  CONSTRAINT `fk_scenario_id_{mth_year}` 
#     FOREIGN KEY (`SCENARIO_ID`) 
#     REFERENCES `scenarios` (`SCENARIO_ID`)
#     ON DELETE SET NULL
#     ON UPDATE CASCADE

   return create_query


def create_query_zblock_transaction_flat(qtr_year):
    """
    This function is used to dynamically create aptransactionflat table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """
    
    table_name = "z_block_transaction_flat_"+str(qtr_year)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    
    CREATE TABLE IF NOT EXISTS {} (
    `audit_id` int,
    `TRANSACTION_ID` int DEFAULT NULL,
    `ACCOUNT_DOC_ID` int DEFAULT NULL,
    `PAYMENT_DATE` datetime DEFAULT NULL,
    `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
    `ENTRY_DATE` datetime DEFAULT NULL,
    `TRANSACTION_CODE` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
    `DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    `POSTING_DATE` datetime DEFAULT NULL,
    `TRANSACTION_DESC` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    `ENTRY_LOCATION` varchar(150) DEFAULT NULL,
    `ENTERED_BY_NAME` varchar(150) DEFAULT NULL,
    `NON_PO_INVOICE` tinyint DEFAULT NULL,
    `TRANSACTION_TEXT_EMPTY` tinyint DEFAULT NULL,
    `ENTERED_BY` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
    `ACCOUNT_NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
    `GL_ACCOUNT_DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    `POSTED_BY` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
    `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
    `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
    `PAYMENT_TERMS` varchar(150) DEFAULT NULL,
    `INVOICE_AMOUNT` decimal(19,2) DEFAULT NULL,
    `DOC_TYPE` varchar(150) DEFAULT NULL,
    `PURCHASE_ORDER_NUMBER` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
    `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
    `CREDIT_PERIOD` int DEFAULT NULL,
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `TRANSACTION_ID` (`TRANSACTION_ID`) USING BTREE,
    KEY `accountdo_idx` (`ACCOUNT_DOC_ID`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    """.format(table_name)
    
    return create_query


def create_query_zblock_account_document_flat(qtr_year):
    """
    This function is used to dynamically create apaccountdocumentflat table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """    
    table_name = "z_block_account_document_flat_"+str(qtr_year)
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
    `batch_id` int,
    `ACCOUNT_DOC_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
    `INVOICE_NUMBER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
    `INVOICE_DATE` datetime DEFAULT NULL,
    `INVOICE_AMOUNT` decimal(19,2) DEFAULT NULL,
    `INVOICE_CURRENCY` varchar(255) DEFAULT NULL,
    `PAYMENT_TERMS` varchar(150) DEFAULT NULL,
    `PAYMENT_METHOD` varchar(255) DEFAULT NULL,
    `VENDOR_NAME` varchar(255) DEFAULT NULL,
    `VENDOR_ADDRESS` varchar(255) DEFAULT NULL,
    `BILL_TO_LEGAL_ENTITY_NAME` varchar(255) DEFAULT NULL,
    `BILL_TO_LEGAL_ENTITY_ADDRESS` varchar(255) DEFAULT NULL,
    `VAT_TAX_CODE` varchar(255) DEFAULT NULL,
    `VAT_TAX_AMOUNT` varchar(255) DEFAULT NULL,
    `BANK_NAME` varchar(255) DEFAULT NULL,
    `BANK_ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
    `INVOICE_RECEIPT_DATE` datetime DEFAULT NULL,
    `DEBIT_AMOUNT` decimal(19,2) DEFAULT NULL,
    `CREDIT_AMOUNT` decimal(19,2) DEFAULT NULL,
    `AMOUNT` decimal(19,2) DEFAULT NULL,
    `ENTRY_ID` varchar(255) DEFAULT NULL,
    `POSTED_DATE` datetime DEFAULT NULL,
    `PAYMENT_DATE` datetime DEFAULT NULL,
    `DUE_DATE` datetime DEFAULT NULL,
    `VENDORCODE` varchar(100) DEFAULT NULL,
    `VAT_ID` varchar(255) DEFAULT NULL,
    `DOC_TYPE` varchar(150) DEFAULT NULL,
    `TRANSACTION_TEXT_EMPTY` tinyint DEFAULT NULL,
    `POSTED_BY_NAME` varchar(150) DEFAULT NULL,
    `COMPANY_CODE_NAME` varchar(150) DEFAULT NULL,
    `POSTED_LOCATION_NAME` varchar(150) DEFAULT NULL,
    `PURCHASE_ORDER_NUMBER` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
    `PURCHASE_ORDER_DATE` datetime DEFAULT NULL,
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `primary_key` (`ACCOUNT_DOC_ID`) USING BTREE,
    KEY `posted_date` (`POSTED_DATE`) USING BTREE,
    KEY `debit` (`DEBIT_AMOUNT`) USING BTREE,
    KEY `credit` (`CREDIT_AMOUNT`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    """.format(table_name)
    
    
    return create_query

def create_query_credit_debit_pairs(audit_id,client_id=None):
    """
    This function is used to dynamically create credit_debit_pairs table query based on audit id
    
    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """
    table_name = "credit_debit_pairs"
    capture_log_message(f'Creating {table_name}')
   
    create_query = f"""
    CREATE TABLE IF NOT EXISTS `{table_name}` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `audit_id` INT DEFAULT NULL,
        `PAIR_ID` INT DEFAULT NULL,
        `COMPANY_CODE` VARCHAR(45) DEFAULT NULL,
        `SUPPLIER_NAME` VARCHAR(255) DEFAULT NULL,
        `INVOICE_NUMBER` VARCHAR(255) DEFAULT NULL,
        `INVOICE_DATE` DATETIME DEFAULT NULL,
        `INVOICE_AMOUNT` DECIMAL(19,2) DEFAULT NULL,
        `DEBIT_CREDIT_INDICATOR` VARCHAR(45) DEFAULT NULL,
        `POSTED_DATE` DATETIME DEFAULT NULL,
        `ENTRY_ID` VARCHAR(45) DEFAULT NULL,
        `PO_NUMBER` VARCHAR(100) DEFAULT NULL,
        `PAIR_TYPE` VARCHAR(45) DEFAULT NULL,
        `is_current_data` bool DEFAULT NULL,
        `REGION` VARCHAR(50) DEFAULT NULL,
        `DOC_TYPE` VARCHAR(50) DEFAULT NULL,
        PRIMARY KEY (`id`),
        INDEX `idx_pair_id` (`PAIR_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """

    return create_query


def create_query_series_dropped_invoices(audit_id,client_id=None):
    """
    This function is used to dynamically create duplicate_invoices table query based on audit id

    Args:
        audit_id : Audit id number
        
    Returns:
        Mysql Create Query
    """
    table_name = "series_duplicate_invoices"
    capture_log_message(f'Creating {table_name}')
    create_query = """
    CREATE TABLE IF NOT EXISTS {} (
    `DUPLICATES_ID` int DEFAULT NULL,
    `ID` int NOT NULL AUTO_INCREMENT,
    `audit_id` int DEFAULT NULL,
    `SCENARIO_ID` INT DEFAULT NULL,
    `RISK_SCORE` varchar(45) DEFAULT NULL,
    `DEBIT_CREDIT_INDICATOR` varchar(10) DEFAULT NULL,
    `PURCHASE_ORDER_NUMBER` varchar(100) DEFAULT NULL,
    `ACCOUNT_DOC_ID` varchar(450) DEFAULT NULL,
    `ENTRY_ID` varchar(45) DEFAULT NULL,
    `ENTRY_TYPE_ID` varchar(45) DEFAULT NULL,
    `INVOICE_NUMBER` varchar(450) DEFAULT NULL,
    `INVOICE_DATE` datetime DEFAULT NULL,
    `INVOICE_AMOUNT` varchar(450) DEFAULT NULL,
    `VENDORCODE` varchar(45)  DEFAULT NULL,
    `VENDOR_NAME` varchar(500) DEFAULT NULL,
    `AMOUNT` varchar(45) DEFAULT NULL,
    `DEBIT_AMOUNT` varchar(45) DEFAULT NULL,
    `CREDIT_AMOUNT` varchar(45) DEFAULT NULL,
    `COMPANYID` bigint DEFAULT NULL,
    `LOCATIONID` varchar(45) DEFAULT NULL,
    `ENTERED_DATE` datetime DEFAULT NULL,
    `POSTED_DATE` datetime DEFAULT NULL,
    `ENTERED_BY` varchar(45) DEFAULT NULL,
    `PAYMENT_DATE` datetime DEFAULT NULL,
    `DUE_DATE` datetime DEFAULT NULL,
    `PAYMENT_TERMS` varchar(500) DEFAULT NULL,
    `CREDIT_PERIOD` varchar(45) DEFAULT NULL,
    `CREATED_DATE` datetime DEFAULT NULL,
    `MODIFIED_DATE` varchar(45) DEFAULT NULL,
    `ACCOUNT_ID` varchar(45) DEFAULT NULL,
    `REVIEWSTATUSID` int DEFAULT '5',
    `PrimaryKeySimple` varchar(450) DEFAULT NULL,
    `INVOICE_NUMBER_FORMAT` varchar(450) DEFAULT NULL,
    `INVOICE_AMOUNT_ABS` varchar(45) DEFAULT NULL,
    `COMPANY` varchar(45) DEFAULT NULL,
    `IS_SCORED` varchar(45) DEFAULT NULL,
    `NO_OF_DUPLICATES` varchar(45) DEFAULT NULL,
    `VENDORID` int DEFAULT NULL,
    `POSTED_BY` int DEFAULT NULL,
    `INVOICE_CATEGORY` varchar(45) DEFAULT NULL,
    `is_current_data` bool DEFAULT NULL,
    `REGION` VARCHAR(50) DEFAULT NULL,
    `DOC_TYPE` VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `inv_date_idx` (`INVOICE_DATE`) USING BTREE,
    KEY `posted_date_idx` (`POSTED_DATE`) USING BTREE,
    KEY `reviewstatus_idx` (`REVIEWSTATUSID`) USING BTREE,
    KEY `compnay_idx` (`COMPANYID`) USING BTREE,
    KEY `vendor_idx` (`VENDORID`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


    """.format(table_name)

    return create_query


# def create_query_ap_transaction_flat_view(audit_id):
#     """
#     This function dynamically creates aptranasction flat view query based on audit id
    
#     Args:
#         audit_id : Audit id number
        
#     Returns:
#         Mysql Create Query
#     """    
    
#     view_name = "aptransactionflatview_"+str(audit_id)
#     ap_transaction_table_name = 'ap_transaction_'+str(audit_id)
#     ap_transaction_score_table_name = 'ap_transactionscore_'+str(audit_id)
#     capture_log_message(f'Creating {view_name}')
#     drop_query = """DROP VIEW IF EXISTS {}""".format(view_name)
#     create_query = """
#     CREATE VIEW {viewname} AS
#     select
#         distinct `aptr`.`audit_id` AS `audit_id`,
#         `aptr`.`TRANSACTION_ID` AS `TRANSACTION_ID`,
#         `aptr`.`ACCOUNT_DOC_ID` AS `ACCOUNT_DOC_ID`,
#         `aptrs`.`CONTROL_DEVIATION` AS `CONTROL_DEVIATION`,
#         `aptr`.`PAYMENT_DATE` AS `PAYMENT_DATE`,
#         `mscoa`.`ACCOUNT_CODE` AS `ACCOUNT_NUMBER`,
#         `aptr`.`ENTRY_DATE` AS `ENTRY_DATE`,
#         `aptr`.`TRANSACTION_CODE` AS `TRANSACTION_CODE`,
#         `aptr`.`GL_ACCOUNT_DESCRIPTION` AS `DESCRIPTION`,
#         `aptr`.`POSTING_DATE` AS `POSTING_DATE`,
#         `aptr`.`TRANSACTION_DESCRIPTION` AS `TRANSACTION_DESC`,
#         `aptrs`.`AI_RISK_SCORE` AS `AI_RISK_SCORE`,
#         `aptrs`.`STAT_SCORE_INDEXED` AS `STAT_SCORE_INDEXED`,
#         `ml`.`LOCATION_CODE` AS `ENTRY_LOCATION`,
#         `mf`.`FMSUSER_CODE` AS `ENTERED_BY_NAME`,
#         `aptrs`.`INVOICES_WITHOUT_GRN` AS `INVOICES_WITHOUT_GRN`,
#         `aptrs`.`DUPLICATE_INVOICE_POSTING` AS `DUPLICATE_INVOICE_POSTING`,
#         `aptrs`.`LATE_PAYMENT` AS `LATE_PAYMENT`,
#         `aptrs`.`EXCESS_PAYMENT` AS `EXCESS_PAYMENT`,
#         `aptrs`.`LOST_DISCOUNT` AS `LOST_DISCOUNT`,
#         `aptrs`.`UNFAVORABLE_PAYMENT_TERMS` AS `UNFAVORABLE_PAYMENT_TERMS`,
#         `aptrs`.`SUSPICIOUS_KEYWORD` AS `SUSPICIOUS_KEYWORD`,
#         `aptrs`.`IMMEDIATE_PAYMENTS` AS `IMMEDIATE_PAYMENTS`,
#         `aptrs`.`POSTING_PERIOD` AS `POSTING_PERIOD`,
#         `aptrs`.`DATE_SEQUENTIAL_MISMATCH` AS `DATE_SEQUENTIAL_MISMATCH`,
#         `aptrs`.`WORK_FLOW_DEVIATION` AS `WORK_FLOW_DEVIATION`,
#         `aptrs`.`TWO_DIGIT_BENFORD` AS `TWO_DIGIT_BENFORD`,
#         `aptrs`.`UNUSUAL_SUPPLIER_ACTIVITY` AS `UNUSUAL_SUPPLIER_ACTIVITY`,
#         `aptrs`.`INVOICE_CREATED_AFTER_ACCOUNTING_DATE` AS `INVOICE_CREATED_AFTER_ACCOUNTING_DATE`,
#         `aptrs`.`INVOICE_VALUE_OF_SUPPLIER` AS `INVOICE_VALUE_OF_SUPPLIER`,
#         `aptrs`.`3_WAY_MATCHING` AS `3_WAY_MATCHING`,
#         `aptrs`.`NON_PO_INVOICE` AS `NON_PO_INVOICE`,
#         `aptrs`.`SEGGREGATION_OF_DUTIES` AS `SEGGREGATION_OF_DUTIES`,
#         `aptrs`.`SIGNIFICANT_DELAY_IN_DELIVERY` AS `SIGNIFICANT_DELAY_IN_DELIVERY`,
#         `aptrs`.`UNUSUAL_VENDOR` AS `UNUSUAL_VENDOR`,
#         `aptrs`.`MANUAL_DEBIT_OR_CREDIT_NOTES` AS `MANUAL_DEBIT_OR_CREDIT_NOTES`,
#         `aptrs`.`ROUNDING_OFF` AS `ROUNDING_OFF`,
#         `aptrs`.`TRANSACTION_TEXT_EMPTY` AS `TRANSACTION_TEXT_EMPTY`,
#         `aptr`.`ENTERED_BY` AS `ENTERED_BY`,
#         `aptr`.`ACCOUNT_NAME` AS `ACCOUNT_NAME`,
#         `aptr`.`INVOICE_ID` AS `INVOICE_ID`,
#         `aptr`.`GL_ACCOUNT_DESCRIPTION` AS `GL_ACCOUNT_DESCRIPTION`,
#         `aptr`.`POSTED_BY` AS `POSTED_BY`,
#         (trim(`aptr`.`DEBIT_AMOUNT`) + 0) AS `DEBIT_AMOUNT`,
#         (trim(`aptr`.`CREDIT_AMOUNT`) + 0) AS `CREDIT_AMOUNT`,
#         (trim(`aptrs`.`BLENDED_RISK_SCORE`) + 0) AS `BLENDED_RISK_SCORE`,
#         (
#         select
#             count(`aptrc`.`TRANSCOMID`)
#         from
#             `ap_transactioncomments` `aptrc`
#         where
#             (`aptrc`.`TRANSACTIONID` = `aptr`.`TRANSACTION_ID`)) AS `COMMENTS`,
#         `aptrs`.`EARLY_POSTED_INVOICES` AS `EARLY_POSTED_INVOICES`,
#         `aptrs`.`OLD_UNPAID_INVOICE` AS `OLD_UNPAID_INVOICE`,
#         `aptrs`.`APPROVAL_MATRIX` AS `APPROVAL_MATRIX`,
#         `aptrs`.`VENDOR_MASTER_CHANGES` AS `VENDOR_MASTER_CHANGES`,
#         `aptrs`.`PAYMENT_BLOCK_R` AS `PAYMENT_BLOCK_R`,
#         `aptrs`.`EARLY_PAYMENT` AS `EARLY_PAYMENT`
        
#     from
#         (((({ap_trans_table} `aptr`
#     join {ap_trans_score_table} `aptrs` on
#         ((`aptr`.`TRANSACTION_ID` = `aptrs`.`TRANSACTION_ID`)))
#     left join `mslocation` `ml` on
#         ((`aptr`.`LOCATION_ID` = `ml`.`LOCATIONID`)))
#     left join `msfmsuser` `mf` on
#         ((`aptr`.`ENTERED_BY` = `mf`.`FMSUSERID`)))
#     left join `mschartofaccounts` `mscoa` on
#         ((`aptr`.`ACCOUNT_ID` = `mscoa`.`ACCOUNTID`)));


#     """.format(viewname=view_name,ap_trans_table = ap_transaction_table_name,ap_trans_score_table=ap_transaction_score_table_name)
    
#     return (drop_query,create_query)


# def create_query_ap_account_document_flat_view(audit_id):
#     """
#     This function dynamically creates apaccount documentflat view query based on audit id
    
#     Args:
#         audit_id : Audit id number
        
#     Returns:
#         Mysql Create Query
#     """
    
#     view_name = "apaccountdocumentsflatview_"+str(audit_id)
#     ap_account_document_table_name = 'ap_accountdocuments_'+str(audit_id)
#     ap_account_document_score_table_name = "ap_accountdocscore_"+str(audit_id)
#     capture_log_message(f'Creating {view_name}')
#     drop_query = """DROP VIEW IF EXISTS {};""".format(view_name)
#     create_query = """
#     CREATE VIEW  {viewname} AS
# select
#     `data`.`audit_id` AS `audit_id`,
#     `data`.`PAYMENT_DATE` AS `PAYMENT_DATE`,
#     `data`.`DUE_DATE` AS `DUE_DATE`,
#     `data`.`INVOICE_DATE` AS `INVOICE_DATE`,
#     `data`.`INVOICE_NUMBER` AS `INVOICE_NUMBER`,
#     `data`.`ACCOUNT_DOC_SCORE_ID` AS `ACCOUNT_DOC_SCORE_ID`,
#     `data`.`ACCOUNT_DOC_ID` AS `ACCOUNT_DOC_ID`,
#     `data`.`DEVIATION` AS `DEVIATION`,
#     `data`.`BLENDED_RISK_SCORE` AS `BLENDED_RISK_SCORE`,
#     `data`.`BLENDED_RISK_SCORE_RAW` AS `BLENDED_RISK_SCORE_RAW`,
#     `data`.`AI_RISK_SCORE` AS `AI_RISK_SCORE`,
#     `data`.`AI_RISK_SCORE_RAW` AS `AI_RISK_SCORE_RAW`,
#     `data`.`STAT_SCORE` AS `STAT_SCORE`,
#     `data`.`STAT_SCORE_INDEXED` AS `STAT_SCORE_INDEXED`,
#     `data`.`RULES_RISK_SCORE` AS `RULES_RISK_SCORE`,
#     `data`.`RULES_RISK_SCORE_RAW` AS `RULES_RISK_SCORE_RAW`,
#     `data`.`CONTROL_DEVIATION` AS `CONTROL_DEVIATION`,
#     `data`.`INVOICES_WITHOUT_GRN` AS `INVOICES_WITHOUT_GRN`,
#     `data`.`DUPLICATE_INVOICE_POSTING` AS `DUPLICATE_INVOICE_POSTING`,
#     `data`.`LATE_PAYMENT` AS `LATE_PAYMENT`,
#     `data`.`EXCESS_PAYMENT` AS `EXCESS_PAYMENT`,
#     `data`.`LOST_DISCOUNT` AS `LOST_DISCOUNT`,
#     `data`.`UNFAVORABLE_PAYMENT_TERMS` AS `UNFAVORABLE_PAYMENT_TERMS`,
#     `data`.`SUSPICIOUS_KEYWORD` AS `SUSPICIOUS_KEYWORD`,
#     `data`.`IMMEDIATE_PAYMENTS` AS `IMMEDIATE_PAYMENTS`,
#     `data`.`POSTING_PERIOD` AS `POSTING_PERIOD`,
#     `data`.`DATE_SEQUENTIAL_MISMATCH` AS `DATE_SEQUENTIAL_MISMATCH`,
#     `data`.`WORK_FLOW_DEVIATION` AS `WORK_FLOW_DEVIATION`,
#     `data`.`TWO_DIGIT_BENFORD` AS `TWO_DIGIT_BENFORD`,
#     `data`.`UNUSUAL_SUPPLIER_ACTIVITY` AS `UNUSUAL_SUPPLIER_ACTIVITY`,
#     `data`.`INVOICE_CREATED_AFTER_ACCOUNTING_DATE` AS `INVOICE_CREATED_AFTER_ACCOUNTING_DATE`,
#     `data`.`INVOICE_VALUE_OF_SUPPLIER` AS `INVOICE_VALUE_OF_SUPPLIER`,
#     `data`.`3_WAY_MATCHING` AS `3_WAY_MATCHING`,
#     `data`.`NON_PO_INVOICE` AS `NON_PO_INVOICE`,
#     `data`.`SEGGREGATION_OF_DUTIES` AS `SEGGREGATION_OF_DUTIES`,
#     `data`.`SIGNIFICANT_DELAY_IN_DELIVERY` AS `SIGNIFICANT_DELAY_IN_DELIVERY`,
#     `data`.`UNUSUAL_VENDOR` AS `UNUSUAL_VENDOR`,
#     `data`.`MANUAL_DEBIT_OR_CREDIT_NOTES` AS `MANUAL_DEBIT_OR_CREDIT_NOTES`,
#     `data`.`ROUNDING_OFF` AS `ROUNDING_OFF`,
#     `data`.`TRANSACTION_TEXT_EMPTY` AS `TRANSACTION_TEXT_EMPTY`,
#     `data`.`STATUS` AS `STATUS`,
#     `data`.`ENTRY_ID` AS `ENTRY_ID`,
#     `data`.`ENTRY_TYPE_ID` AS `ENTRY_TYPE_ID`,
#     `data`.`VENDORID` AS `VENDORID`,
#     `data`.`POSTED_DATE` AS `POSTED_DATE`,
#     `data`.`COMPANYID` AS `COMPANYID`,
#     `data`.`LOCATIONID` AS `LOCATIONID`,
#     `data`.`POSTED_LOCATION_NAME` AS `POSTED_LOCATION_NAME`,
#     `data`.`DEBIT_AMOUNT` AS `DEBIT_AMOUNT`,
#     `data`.`CREDIT_AMOUNT` AS `CREDIT_AMOUNT`,
#     `data`.`POSTED_BY_NAME` AS `POSTED_BY_NAME`,
#     `data`.`COMPANY_CODE_NAME` AS `COMPANY_CODE_NAME`,
#     `data`.`REVIEWSTATUSID` AS `REVIEWSTATUSID`,
#     `data`.`REVIEW_STATUS_CODE` AS `REVIEW_STATUS_CODE`,
#     `data`.`COMMENTS` AS `COMMENTS`,
#     `data`.`ASSIGNED_TO` AS `ASSIGNED_TO`,
#     `data`.`ASSIGNED_BY` AS `ASSIGNED_BY`,
#     `data`.`ISDEVIATION` AS `ISDEVIATION`,
#     `data`.`SELECTED_TRANSACTIONS` AS `SELECTED_TRANSACTIONS`,
#     `data`.`SUB_R_STATUS_CODE` AS `SUB_R_STATUS_CODE`,
#     `data`.`SUBRSTATUSID` AS `SUBRSTATUSID`,
#     `data`.`EARLY_POSTED_INVOICES` AS `EARLY_POSTED_INVOICES`,
#     `data`.`OLD_UNPAID_INVOICE` AS `OLD_UNPAID_INVOICE`,
#     `data`.`APPROVED_USER_1` AS `APPROVED_USER_1`,
#     `data`.`APPROVED_USER_2` AS `APPROVED_USER_2`,
#     `data`.`APPROVED_USER_3` AS `APPROVED_USER_3`,
#     `data`.`APPROVED_USER_4` AS `APPROVED_USER_4`,
#     `data`.`APPROVED_USER_5` AS `APPROVED_USER_5`,
#     `data`.`APPROVAL_MATRIX_ID` AS `APPROVAL_MATRIX_ID`,
#     `data`.`APPROVAL_MATRIX` AS `APPROVAL_MATRIX`,
#     `data`.`VENDOR_MASTER_CHANGES` AS `VENDOR_MASTER_CHANGES`,
#     `data`.`VENDORCODE` AS `VENDORCODE`,
#     `data`.`PAYMENT_BLOCK_R` AS `PAYMENT_BLOCK_R`,
#     `data`.`EARLY_PAYMENT` AS `EARLY_PAYMENT`
# from
#     (
#     select
#         distinct `doc`.`audit_id` AS `audit_id`,
#         `doc`.`PAYMENT_DATE` AS `PAYMENT_DATE`,
#         `doc`.`DUE_DATE` AS `DUE_DATE`,
#         `doc`.`INVOICE_DATE` AS `INVOICE_DATE`,
#         `doc`.`INVOICE_NUMBER` AS `INVOICE_NUMBER`,
#         `sco`.`ACCOUNT_DOC_SCORE_ID` AS `ACCOUNT_DOC_SCORE_ID`,
#         `sco`.`ACCOUNT_DOC_ID` AS `ACCOUNT_DOC_ID`,
#         `sco`.`DEVIATION` AS `DEVIATION`,
#         `sco`.`BLENDED_RISK_SCORE` AS `BLENDED_RISK_SCORE`,
#         `sco`.`BLENDED_RISK_SCORE_RAW` AS `BLENDED_RISK_SCORE_RAW`,
#         `sco`.`AI_RISK_SCORE` AS `AI_RISK_SCORE`,
#         `sco`.`AI_RISK_SCORE_RAW` AS `AI_RISK_SCORE_RAW`,
#         `sco`.`STAT_SCORE` AS `STAT_SCORE`,
#         `sco`.`STAT_SCORE_INDEXED` AS `STAT_SCORE_INDEXED`,
#         `sco`.`RULES_RISK_SCORE` AS `RULES_RISK_SCORE`,
#         `sco`.`RULES_RISK_SCORE_RAW` AS `RULES_RISK_SCORE_RAW`,
#         `sco`.`CONTROL_DEVIATION` AS `CONTROL_DEVIATION`,
#         `sco`.`INVOICES_WITHOUT_GRN` AS `INVOICES_WITHOUT_GRN`,
#         `sco`.`DUPLICATE_INVOICE_POSTING` AS `DUPLICATE_INVOICE_POSTING`,
#         `sco`.`OLD_UNPAID_INVOICE` AS `OLD_UNPAID_INVOICE`,
#         `sco`.`LATE_PAYMENT` AS `LATE_PAYMENT`,
#         `sco`.`EARLY_PAYMENT` AS `EARLY_PAYMENT`,
#         `sco`.`EXCESS_PAYMENT` AS `EXCESS_PAYMENT`,
#         `sco`.`LOST_DISCOUNT` AS `LOST_DISCOUNT`,
#         `sco`.`APPROVAL_MATRIX` AS `APPROVAL_MATRIX`,
#         `sco`.`UNFAVORABLE_PAYMENT_TERMS` AS `UNFAVORABLE_PAYMENT_TERMS`,
#         `sco`.`SUSPICIOUS_KEYWORD` AS `SUSPICIOUS_KEYWORD`,
#         `sco`.`IMMEDIATE_PAYMENTS` AS `IMMEDIATE_PAYMENTS`,
#         `sco`.`POSTING_PERIOD` AS `POSTING_PERIOD`,
#         `sco`.`DATE_SEQUENTIAL_MISMATCH` AS `DATE_SEQUENTIAL_MISMATCH`,
#         `sco`.`WORK_FLOW_DEVIATION` AS `WORK_FLOW_DEVIATION`,
#         `sco`.`TWO_DIGIT_BENFORD` AS `TWO_DIGIT_BENFORD`,
#         `sco`.`UNUSUAL_SUPPLIER_ACTIVITY` AS `UNUSUAL_SUPPLIER_ACTIVITY`,
#         `sco`.`PAYMENT_BLOCK_R` AS `PAYMENT_BLOCK_R`,
#         `sco`.`INVOICE_CREATED_AFTER_ACCOUNTING_DATE` AS `INVOICE_CREATED_AFTER_ACCOUNTING_DATE`,
#         `sco`.`VENDOR_MASTER_CHANGES` AS `VENDOR_MASTER_CHANGES`,
#         `sco`.`INVOICE_VALUE_OF_SUPPLIER` AS `INVOICE_VALUE_OF_SUPPLIER`,
#         `sco`.`3_WAY_MATCHING` AS `3_WAY_MATCHING`,
#         `sco`.`NON_PO_INVOICE` AS `NON_PO_INVOICE`,
#         `sco`.`SEGGREGATION_OF_DUTIES` AS `SEGGREGATION_OF_DUTIES`,
#         `sco`.`SIGNIFICANT_DELAY_IN_DELIVERY` AS `SIGNIFICANT_DELAY_IN_DELIVERY`,
#         `sco`.`UNUSUAL_VENDOR` AS `UNUSUAL_VENDOR`,
#         `sco`.`MANUAL_DEBIT_OR_CREDIT_NOTES` AS `MANUAL_DEBIT_OR_CREDIT_NOTES`,
#         `sco`.`ROUNDING_OFF` AS `ROUNDING_OFF`,
#         `sco`.`TRANSACTION_TEXT_EMPTY` AS `TRANSACTION_TEXT_EMPTY`,
#         `sco`.`EARLY_POSTED_INVOICES` AS `EARLY_POSTED_INVOICES`,
#         `sco`.`STATUS` AS `STATUS`,
#         `doc`.`ENTRY_ID` AS `ENTRY_ID`,
#         `doc`.`ENTRY_TYPE_ID` AS `ENTRY_TYPE_ID`,
#         `doc`.`VENDORID` AS `VENDORID`,
#         `av`.`VENDORCODE` AS `VENDORCODE`,
#         `doc`.`POSTED_DATE` AS `POSTED_DATE`,
#         `doc`.`COMPANYID` AS `COMPANYID`,
#         `doc`.`LOCATIONID` AS `LOCATIONID`,
#         `ml`.`LOCATION_CODE` AS `POSTED_LOCATION_NAME`,
#         (trim(`doc`.`DEBIT_AMOUNT`) + 0) AS `DEBIT_AMOUNT`,
#         (trim(`doc`.`CREDIT_AMOUNT`) + 0) AS `CREDIT_AMOUNT`,
#         `usr`.`FMSUSER_CODE` AS `POSTED_BY_NAME`,
#         `com`.`COMPANY_CODE` AS `COMPANY_CODE_NAME`,
#         `ws`.`REVIEWSTATUSID` AS `REVIEWSTATUSID`,
#         `ws`.`REVIEW_STATUS_CODE` AS `REVIEW_STATUS_CODE`,
#         ifnull(`assign_comments`.`COMMENTS`, 0) AS `COMMENTS`,
#         `assign_comments`.`ASSIGNED_TO` AS `ASSIGNED_TO`,
#         `assign_comments`.`ASSIGNED_BY` AS `ASSIGNED_BY`,
#         `assign_comments`.`ISDEVIATION` AS `ISDEVIATION`,
#         `assign_comments`.`TRANSACTIONS` AS `SELECTED_TRANSACTIONS`,
#         `assign_comments`.`SUB_R_STATUS_CODE` AS `SUB_R_STATUS_CODE`,
#         `assign_comments`.`SUBRSTATUSID` AS `SUBRSTATUSID`,
#         `doc`.`APPROVED_USER_1` AS `APPROVED_USER_1`,
#         `doc`.`APPROVED_USER_2` AS `APPROVED_USER_2`,
#         `doc`.`APPROVED_USER_3` AS `APPROVED_USER_3`,
#         `doc`.`APPROVED_USER_4` AS `APPROVED_USER_4`,
#         `doc`.`APPROVED_USER_5` AS `APPROVED_USER_5`,
#         `doc`.`APPROVAL_MATRIX_ID` AS `APPROVAL_MATRIX_ID`
#     from
#         ((((((({ap_acc_doc_table} `doc`
#     join `{ap_acc_doc_score_table}` `sco` on
#         ((`doc`.`ACCOUNT_DOC_ID` = `sco`.`ACCOUNT_DOC_ID`)))
#     join `trworkflowstatus` `ws` on
#         ((`doc`.`REVIEWSTATUSID` = `ws`.`REVIEWSTATUSID`)))
#     left join `msfmsuser` `usr` on
#         ((`doc`.`POSTED_BY` = `usr`.`FMSUSERID`)))
#     left join `mscompany` `com` on
#         ((`doc`.`COMPANYID` = `com`.`COMPANYID`)))
#     left join `mslocation` `ml` on
#         ((`doc`.`LOCATIONID` = `ml`.`LOCATIONID`)))
#     left join `ap_vendorlist` `av` on
#         ((`doc`.`VENDORID` = `av`.`VENDORID`)))
#     left join (
#         select
#             `comments`.`ACCOUNT_DOC_ID` AS `ACCOUNT_DOC_ID`,
#             `comments`.`COMMENTS` AS `COMMENTS`,
#             `assigns`.`ASSIGNED_TO` AS `ASSIGNED_TO`,
#             `assigns`.`ASSIGNED_BY` AS `ASSIGNED_BY`,
#             `assigns`.`ISDEVIATION` AS `ISDEVIATION`,
#             `assigns`.`TRANSACTIONS` AS `TRANSACTIONS`,
#             `assigns`.`SUB_R_STATUS_CODE` AS `SUB_R_STATUS_CODE`,
#             `assigns`.`SUBRSTATUSID` AS `SUBRSTATUSID`
#         from
#             ((
#             select
#                 `ap_accountdocumentuser`.`ACCOUNT_DOC_ID` AS `ACCOUNT_DOC_ID`,
#                 count(0) AS `COMMENTS`
#             from
#                 `ap_accountdocumentuser`
#             group by
#                 `ap_accountdocumentuser`.`ACCOUNT_DOC_ID`) `comments`
#         join (
#             select
#                 `dusr`.`ACCOUNT_DOC_ID` AS `ACCOUNT_DOC_ID`,
#                 `dusr`.`ASSIGNED_TO` AS `ASSIGNED_TO`,
#                 `dusr`.`ASSIGNED_BY` AS `ASSIGNED_BY`,
#                 `dusr`.`ISDEVIATION` AS `ISDEVIATION`,
#                 `dusr`.`TRANSACTIONS` AS `TRANSACTIONS`,
#                 `sub`.`SUB_R_STATUS_CODE` AS `SUB_R_STATUS_CODE`,
#                 `dusr`.`SUBRSTATUSID` AS `SUBRSTATUSID`
#             from
#                 (`ap_accountdocumentuser` `dusr`
#             join `trsubworkflowstatus` `sub` on
#                 ((`dusr`.`SUBRSTATUSID` = `sub`.`SUBRSTATUSID`)))
#             where
#                 (`dusr`.`STATUS` = 1)) `assigns` on
#             ((`comments`.`ACCOUNT_DOC_ID` = `assigns`.`ACCOUNT_DOC_ID`)))) `assign_comments` on
#         ((`doc`.`ACCOUNT_DOC_ID` = `assign_comments`.`ACCOUNT_DOC_ID`)))) `data`;

    
#     """.format(viewname = view_name,ap_acc_doc_table=ap_account_document_table_name,
#                ap_acc_doc_score_table = ap_account_document_score_table_name,)
    
#     return (drop_query,create_query)