# WITH - Withold Tax Code Rename Map
WITHHOLD_TAX_RENAME_MAP = {
    'MANDT':'CLIENT',
    'BUKRS':'COMPANY_CODE',
    'BELNR':'DOCUMENT_NUMBER',
    'GJAHR':'FISCAL_YEAR',
    'BUZEI':'ACCOUNTING_LINE_ITEM',
    'WITHT':'WITHHOLD_TAX_TYPE',
    'WT_WITHCD':'WITHHOLD_TAX_CODE',
    'WT_QSSHH':'WITHHOLD_TAX_BASE_LC',
    'WT_QSSHB':'WITHHOLD_TAX_BASE_FC',
    }

